on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      - name: Build
        run: npm i -g pnpm && pnpm i && npx prisma generate --data-proxy && pnpm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ela-platform # e.g. 'my-project'
          directory: ./.svelte-kit/cloudflare # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
